### ISSUE TITLE
Window picker lags while scrolling through the doc options

### ISSUE THREAD

**Issue by I-Own-You** [luckasRanarison/nvim-devdocs#18] opened 2023-08-13 17:26 UTC
There is a problem that i encountered _**1 day ago**_. 
When i _**enter**_ in the _**window where i need to pick the documentation**_ and i start to scroll (like hold the ctrl+n or ctrl+p), it lagged and _**after i released the key**_, it went down by n rows.
 _**After the update**_, now, i cant even press ctrl+p or ctrl+n _**without waiting 2-3 secs to see the changes**_.
 <p>For now i will disable the previewer in the source file, so i would not have lags while scrolling/going up/down</p>

**Comment by luckasRanarison** [comment] 2023-08-13 17:32
Could you precise the docs you used? I'm aware of the performance issues and I'm working on it.

**Comment by I-Own-You** [comment] 2023-08-13 17:35
> Could you precise the docs you used? I'm aware of the performance issues and I'm working on it.

all of them i have: go, django, javascript, typescript, lua, tailwind, html, django-rest-framework

**Comment by luckasRanarison** [comment] 2023-08-13 17:43
There are no real performance improvement I can make at the moment because the plugin is directly fetching all the entries before opening the picker... The ideal would be to split the entries in different files as suggested in #14 and dynamically read them when using the picker

**Comment by I-Own-You** [comment] 2023-08-13 17:45
take your time, no one is in hurry, ill just disable the previewer. Thanks for your work 💘

**Comment by luckasRanarison** [comment] 2023-08-15 18:01
#21 has slightly improved the picker performance but scrolling through docs with a single entry like `lua-5.4` and `lodash-4` is still laggy.

**Comment by I-Own-You** [comment] 2023-08-15 18:35
is `picker_cmd = false ` supposed to prevent preview of the markdown ?

**Comment by emmanueltouzery** [comment] 2023-08-23 20:51
I don't really understand; I thought #17 and #21 would mean that for lodash we'd get multiple files in the devdocs data folder, and that these files would have been pre-processed by glow, but I see there is still a single md file, which explains the performance issues when scrolling.
I have trouble reconciling that with the description of what #17 and #21 was supposed to be doing :thinking: ?

**Comment by luckasRanarison** [comment] 2023-08-23 21:47
Sorry for the misunderstanding, actually the docs are splited in "main entries" which are already defined by the index.json and the website used the same method. Most of the docs have like 1000 main entries so I thought it'd be more complex to split it further at the `section` level. Maybe I could handle these docs as special cases. Also a note, glow itself is really **slow**.

**Comment by emmanueltouzery** [comment] 2023-08-24 17:06
the glow PR was now merged and I can confirm the preview speed has now reduced to like 1-2 seconds for lodash.

However I can now see that it's displaying the whole lodash docs, not only the only for the selected functions, but that's covered by other bugs.

1-2 seconds is still lagging, but it's usable, while before it wasn't. But obviously a new version of glow must be released. But to fix the scrolling at the position of the current function/displaying only the current function maybe it'll be necessary to split the output anyway (I just don't know).

**Comment by luckasRanarison** [comment] 2023-08-25 06:17
Lodash docs are still messy at the moment because the converter can't handle nested tables and rowspan. Jumping with glow should already work, except for the telescope window (I need help with that). So, splitting isn't necessary. The reason why some jumps don't work is likely due to the incorrect path to the section.

**Comment by luckasRanarison** [comment] 2023-09-13 10:58
Closing this as completed, see #42

**Closed by luckasRanarison** 2023-09-13 10:58 UTC
