### ISSUE TITLE
Fetching cpp documentation entries...Downloading cpp documentation...PANIC: unprotected error in call to Lua API (not enough memory)

### ISSUE THREAD

**Issue by 5i1ent** [luckasRanarison/nvim-devdocs#39] opened 2023-09-03 11:44 UTC
`NVIM v0.10.0-dev`
`Build type: RelWithDebInfo`
`LuaJIT 2.1.0-beta3`

`curl 7.81.0 (x86_64-pc-linux-gnu) ` - if related.

python-3.11 docs installed fine.

`nvim --headless +"DevdocsInstall cpp"` throws:

`Fetching cpp documentation entries...Downloading cpp documentation...PANIC: unprotected error in call to Lua API (not enough memory)`

also fails to install cpp docs inside neovim using `DevdocsInstall`. It's just closes neovim without any error.

**Comment by luckasRanarison** [comment] 2023-09-03 13:40
How many RAM do you have? I've observed high memory usage when building some documentations and I think it's because of the write process. The documentation entries are split into multiple files, and the cpp documentation has 4642 entries, so 4642 files need to be written to the disk. I'm still thinking on a way to handle the build process more efficiently.

**Comment by 5i1ent** [comment] 2023-09-03 13:46
16gb

**Comment by luckasRanarison** [comment] 2023-09-03 13:54
>  it not even reach compilation.

Oh sorry, I only realize it now, it effectively failed in the download part. But I still can't reproduce the error.

Using curl 7.85.0
NVIM v0.10.0-dev+741-g996dd36c7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by 5i1ent** [comment] 2023-09-03 15:36
neovim related issue

works fine on:
`NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3`

**Comment by luckasRanarison** [comment] 2023-09-13 03:57
Closing this as completed.

**Closed by luckasRanarison** 2023-09-13 03:57 UTC
Labels: bug
